experiment: ref_single_CTCF_ENC-001_all_tissues_AS_baltrain
ref_fasta: /home/asm242/reference_genome/hg38.fa
output_dir: /home/asm242/entexBERT-2/AS/1/CTCF/all_tissues/ref_single_classification_256_256_jitter50_baltrain/input

row_source:
  type: snv_tsv
  path: /home/asm242/entex_data/hetSNVs.tsv
  assay: TF-ChIP-seq_CTCF
  donor: ENC-001
  tissue: ALL
  min_total_reads: 10
  chunksize: 100000

primary_label: {type: as_class}
aux_labels: []

sequence: {input_mode: ref_single}

window:
  left_bp: 256
  right_bp: 256
  chrom_sizes: /home/asm242/reference_genome/hg38.chrom.sizes
  snv_offset_mode: uniform
  jitter_max_bp: 50

balance: {strategy: per_tissue_binary, label_col: imbalance_significance, apply_to: train}

split:
  mode: train_dev_test
  ratio: [0.8, 0.1, 0.1]
  seed: 42
  group: locus
  skip_ambiguous: true

head: {num_labels: 2, head_num_layers: 1, head_hidden_size: -1}
