experiment: ref_alt_pair_CTCF_ENC-001_all_tissues_ASreg_signedlogaltref
ref_fasta: /home/asm242/reference_genome/hg38.fa
output_dir: /home/asm242/entexBERT-2/AS/1/CTCF/all_tissues/ref_alt_pair_regression_256_256_jitter50_signedlogaltref/input

row_source:
  type: snv_tsv
  path: /home/asm242/entex_data/hetSNVs.tsv
  assay: TF-ChIP-seq_CTCF
  donor: ENC-001
  tissue: ALL
  min_total_reads: 20
  chunksize: 100000

primary_label: {type: as_regression, target: signed_log_alt_ref}
aux_labels: []

sequence: {input_mode: ref_alt_pair}

window:
  left_bp: 256
  right_bp: 256
  chrom_sizes: /home/asm242/reference_genome/hg38.chrom.sizes
  snv_offset_mode: uniform
  jitter_max_bp: 50

balance: {strategy: none}

split:
  mode: train_dev_test
  ratio: [0.8, 0.1, 0.1]
  seed: 42
  group: locus
  skip_ambiguous: true

head: {num_labels: 1, head_num_layers: 2, head_hidden_size: -1}
